stages:
  - test
  - build
  - deploy
  - sync

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # We want full history so that "git describe" always works correctly.
  GIT_DEPTH: 0
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"
  # We always want to run with the Go version installed in a Docker image.
  GOTOOLCHAIN: local

test:
  stage: test

  image: golang:1.21-alpine3.18

  services:
    - name: registry.gitlab.com/tozd/docker/postgresql:16
      alias: postgres
      variables:
        LOG_TO_STDOUT: 1
        PGSQL_ROLE_1_USERNAME: test
        PGSQL_ROLE_1_PASSWORD: test
        PGSQL_DB_1_NAME: test
        PGSQL_DB_1_OWNER: test

  variables:
    TIME: 1m
    POSTGRES: "postgres://test:test@postgres:5432"

  before_script:
    - apk --update add make bash gcc musl-dev

  script:
    - make benchmark

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - badger
        - bbolt
        - bitcask
        - buntdb
        - fs
        - immudb
        - nutsdb
        - pebble
        - postgresql
        - postgresqllo
        - sqlite

lint:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

  script:
    - make lint-ci

  artifacts:
    when: always
    reports:
      codequality: codeclimate.json
    expire_in: never

fmt:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev grep
    - go install mvdan.cc/gofumpt@v0.5.0
    - go install golang.org/x/tools/cmd/goimports@v0.13.0

  script:
    - make fmt-ci

lint_docs:
  stage: test

  image: node:17-alpine3.14

  before_script:
    - apk --update add make bash

  script:
    - make lint-docs

audit:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev
    - go install github.com/sonatype-nexus-community/nancy@v1.0.42

  script:
    - make audit

commits:
  stage: test

  image: golang:1.21-alpine3.18

  variables:
    GIT_DEPTH: "0"

  before_script:
    - apk --update add git

  script:
    - '! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep "^"'

benchmark:
  stage: build

  image: golang:1.21-alpine3.18

  tags:
    - saas-linux-2xlarge-amd64

  variables:
    TIME: 20m

  before_script:
    - apk --update add make bash gcc musl-dev

  script:
    - make benchmark

  allow_failure: true

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - badger
        - bbolt
        - bitcask
        - buntdb
        - fs
        - immudb
        - nutsdb
        - pebble
        - sqlite
      - READERS: ['1']
      - WRITERS: ['1']
      - SIZE: ['100B']
      - VARY: ['false']
      # Twice the number of cores on saas-linux-2xlarge-amd64 machine to put load on I/O.
      - GOMAXPROCS: ['4']

  rules:
    # We benchmark on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

benchmark_postgres:
  stage: build

  image: golang:1.21-alpine3.18

  tags:
    - saas-linux-2xlarge-amd64

  services:
    - name: registry.gitlab.com/tozd/docker/postgresql:16
      alias: postgres
      variables:
        LOG_TO_STDOUT: 1
        PGSQL_ROLE_1_USERNAME: test
        PGSQL_ROLE_1_PASSWORD: test
        PGSQL_DB_1_NAME: test
        PGSQL_DB_1_OWNER: test

  variables:
    TIME: 20m
    POSTGRES: "postgres://test:test@postgres:5432"

  before_script:
    - apk --update add make bash gcc musl-dev

  script:
    - make benchmark

  allow_failure: true

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - postgresql
        - postgresqllo
      - READERS: ['1']
      - WRITERS: ['1']
      - SIZE: ['100B']
      - VARY: ['false']
      # Twice the number of cores on saas-linux-2xlarge-amd64 machine to put load on I/O.
      - GOMAXPROCS: ['4']

  rules:
    # We benchmark and publish results on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

pages:
  stage: deploy

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev

  script:
    - make plot

  artifacts:
    paths:
      - index.html
    expire_in: never

  rules:
    # We benchmark and publish results on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

  dependencies:
    - benchmark
    - benchmark_postgres

sync_config:
  stage: sync

  image:
    name: registry.gitlab.com/tozd/gitlab/config/tag/v0-5-0:latest-debug
    entrypoint: [""]

  script:
    - /gitlab-config set

  rules:
    - if: '$GITLAB_API_TOKEN && $SOPS_AGE_KEY_FILE && $CI_COMMIT_BRANCH == "main"'
      changes:
        - .gitlab-conf.yml

  # We do not need build artifacts in this job.
  dependencies: []
