stages:
  - test
  - build
  - deploy
  - sync

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # We want full history so that "git describe" always works correctly.
  GIT_DEPTH: 0
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"
  # We always want to run with the Go version installed in a Docker image.
  GOTOOLCHAIN: local

test:
  stage: test

  image: golang:1.21-alpine3.18

  services:
    - name: registry.gitlab.com/tozd/docker/postgresql:16
      alias: postgres
      variables:
        LOG_TO_STDOUT: 1
        PGSQL_ROLE_1_USERNAME: test
        PGSQL_ROLE_1_PASSWORD: test
        PGSQL_DB_1_NAME: test
        PGSQL_DB_1_OWNER: test

  variables:
    TIME: 1m
    POSTGRES: "postgres://test:test@postgres:5432"

  before_script:
    - apk --update add make bash gcc musl-dev

  script:
    - make benchmark

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - badger
        - bbolt
        - bitcask
        - buntdb
        - fs
        - immudb
        - nutsdb
        - pebble
        - postgresql
        - postgresqllo
        - sqlite

lint:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

  script:
    - make lint-ci

  artifacts:
    when: always
    reports:
      codequality: codeclimate.json
    expire_in: never

fmt:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev grep
    - go install mvdan.cc/gofumpt@v0.5.0
    - go install golang.org/x/tools/cmd/goimports@v0.13.0

  script:
    - make fmt-ci

lint_docs:
  stage: test

  image: node:17-alpine3.14

  before_script:
    - apk --update add make bash

  script:
    - make lint-docs

audit:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev
    - go install github.com/sonatype-nexus-community/nancy@v1.0.42

  script:
    - make audit

commits:
  stage: test

  image: golang:1.21-alpine3.18

  variables:
    GIT_DEPTH: "0"

  before_script:
    - apk --update add git

  script:
    - '! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep "^"'
