stages:
  - test
  - build
  - deploy
  - sync

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # We want full history so that "git describe" always works correctly.
  GIT_DEPTH: 0
  FF_ENABLE_BASH_EXIT_CODE_CHECK: "true"
  # We always want to run with the Go version installed in a Docker image.
  GOTOOLCHAIN: local

test:
  stage: test

  image: golang:1.21-alpine3.18

  services:
    - name: registry.gitlab.com/tozd/docker/postgresql:16
      alias: postgres
      variables:
        LOG_TO_STDOUT: 1
        PGSQL_ROLE_1_USERNAME: test
        PGSQL_ROLE_1_PASSWORD: test
        PGSQL_DB_1_NAME: test
        PGSQL_DB_1_OWNER: test

  variables:
    TIME: 1m
    POSTGRES: "postgres://test:test@postgres:5432"
    # We list defaults so that log filenames have these values in it.
    READERS: 1
    WRITERS: 1
    SIZE: 1MB
    VARY: "false"

  before_script:
    - apk --update add make bash gcc musl-dev
    - ulimit -a

  script:
    - make benchmark

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - badger
        - bbolt
        - bitcask
        - buntdb
        - fs
        - immudb
        - nutsdb
        - pebble
        - postgresql
        - postgresqllo
        - sqlite

lint:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

  script:
    - make lint-ci

  artifacts:
    when: always
    reports:
      codequality: codeclimate.json
    expire_in: never

fmt:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev grep
    - go install mvdan.cc/gofumpt@v0.5.0
    - go install golang.org/x/tools/cmd/goimports@v0.13.0

  script:
    - make fmt-ci

lint_docs:
  stage: test

  image: node:17-alpine3.14

  before_script:
    - apk --update add make bash

  script:
    - make lint-docs

audit:
  stage: test

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash git gcc musl-dev
    - go install github.com/sonatype-nexus-community/nancy@v1.0.42

  script:
    - make audit

commits:
  stage: test

  image: golang:1.21-alpine3.18

  variables:
    GIT_DEPTH: "0"

  before_script:
    - apk --update add git

  script:
    - '! git log --oneline "-G^(<<<<<<<|=======|>>>>>>>)" | grep "^"'

# Matrix can make at most 200 jobs, so we split it into two main jobs based on SIZE.
benchmark:
  stage: build

  image: golang:1.21-alpine3.18

  tags:
    # We need XFS file system for fsclone engine.
    - xfs

  variables:
    TIME: 20m
    VARY: "true"
    # Twice the number of cores to put load on I/O.
    THREADS_MULTIPLIER: 2

  before_script:
    - apk --update add make bash gcc musl-dev
    - ulimit -a

  script:
    - make benchmark

  allow_failure: true

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - badger
        - bbolt
        # Failing on xfs.
        # See: https://git.mills.io/prologic/bitcask/issues/261
        # - bitcask
        - buntdb
        - fs
        - fsclone
        - immudb
        - nutsdb
        - pebble
        - sqlite
        READERS: ['1', '50', '100']
        WRITERS: ['1', '10', '50']
        SIZE: ['100B', '32KB']

  rules:
    # We benchmark and publish results on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

# Matrix can make at most 200 jobs, so we split it into two main jobs based on SIZE.
benchmark_large:
  stage: build

  image: golang:1.21-alpine3.18

  tags:
    # We need XFS file system for fsclone engine.
    - xfs

  variables:
    TIME: 20m
    VARY: "true"
    # Twice the number of cores to put load on I/O.
    THREADS_MULTIPLIER: 2

  before_script:
    - apk --update add make bash gcc musl-dev
    - ulimit -a

  script:
    - make benchmark

  allow_failure: true

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - badger
        - bbolt
        # Failing on xfs.
        # See: https://git.mills.io/prologic/bitcask/issues/261
        # - bitcask
        - buntdb
        - fs
        - fsclone
        - immudb
        - nutsdb
        - pebble
        - sqlite
        READERS: ['1', '50', '100']
        WRITERS: ['1', '10', '50']
        SIZE: ['5MB', '500MB']

  rules:
    # We benchmark and publish results on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

benchmark_postgres:
  stage: build

  image: golang:1.21-alpine3.18

  tags:
    # Use same runners as for the non-Postgresql engines (where fsclone engine requires XFS file system).
    - xfs

  services:
    - name: registry.gitlab.com/tozd/docker/postgresql:16
      alias: postgres
      variables:
        LOG_TO_STDOUT: 1
        PGSQL_ROLE_1_USERNAME: test
        PGSQL_ROLE_1_PASSWORD: test
        PGSQL_DB_1_NAME: test
        PGSQL_DB_1_OWNER: test

  variables:
    TIME: 20m
    VARY: "true"
    POSTGRES: "postgres://test:test@postgres:5432"
    # Twice the number of cores to put load on I/O.
    THREADS_MULTIPLIER: 2

  before_script:
    - apk --update add make bash gcc musl-dev
    - ulimit -a

  script:
    - make benchmark

  allow_failure: true

  artifacts:
    when: always
    paths:
      - "*.log"
    expire_in: never

  parallel:
    matrix:
      - ENGINE:
        - postgresql
        - postgresqllo
        READERS: ['1', '50', '100']
        WRITERS: ['1', '10', '50']
        SIZE: ['100B', '32KB', '5MB', '500MB']

  rules:
    # We benchmark and publish results on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

pages:
  stage: deploy

  image: golang:1.21-alpine3.18

  before_script:
    - apk --update add make bash gcc musl-dev

  script:
    - make plot
    - mkdir public
    - mv *.log *.html public

  artifacts:
    paths:
      - public
    expire_in: never

  rules:
    # We benchmark and publish results on every change of the main branch.
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PROJECT_PATH == "go-benchmark-kvstore/go-benchmark-kvstore.gitlab.io"'

  dependencies:
    - benchmark
    - benchmark_large
    - benchmark_postgres

sync_config:
  stage: sync

  image:
    name: registry.gitlab.com/tozd/gitlab/config/tag/v0-5-0:latest-debug
    entrypoint: [""]

  script:
    - /gitlab-config set

  rules:
    - if: '$GITLAB_API_TOKEN && $SOPS_AGE_KEY_FILE && $CI_COMMIT_BRANCH == "main"'
      changes:
        - .gitlab-conf.yml

  # We do not need build artifacts in this job.
  dependencies: []
